#!/bin/bash

current_pid=$$
process_name="bash"

for pid in /proc/*/; do
    pid=${pid%/}
    pid=${pid##*/}
    
    # Check if the PID is a number
    if [[ $pid =~ ^[0-9]+$ ]]; then
        process_cmdline=$(tr '\0' ' ' < "/proc/$pid/cmdline")

        # Check if the process name contains the word "bash"
        if grep -q "$process_name" <<< "$process_cmdline"; then
            echo "$pid $process_cmdline"
        fi
    fi
done
